package com.auramusic.app.subtitles

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight

data class SubtitleInfo(
    val url: String,
    val format: String,
    val language: String,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val cachedContent: String? = null,
    val cachedFilePath: String? = null
)

data class SubtitleCue(
    val startMs: Long,
    val endMs: Long,
    val text: String
)

data class SubtitleStyle(
    val fontSize: Float = 16f,
    val textColor: Color = Color.White,
    val backgroundColor: Color = Color.Black.copy(alpha = 0.7f),
    val fontWeight: FontWeight = FontWeight.Normal
)

data class SubtitleOption(
    val label: String,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val info: SubtitleInfo
)